# Generated by Django 3.2.8 on 2021-10-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_site_admin',
            field=models.BooleanField(default=False),
        ),
    ]
