# Generated by Django 3.2.8 on 2021-10-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_site_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
