# Generated by Django 3.2.8 on 2021-10-17 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_team_super12'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('super12', 'Super 12'), ('sf', 'Semi Final'), ('final', 'Final')], default='super12', max_length=10)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('venue', models.CharField(max_length=200)),
                ('min_bet', models.PositiveSmallIntegerField(default=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='scheduled', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.CharField(max_length=10, validators=[main.models.score_validator])),
                ('team2_score', models.CharField(max_length=10, validators=[main.models.score_validator])),
                ('win_type', models.CharField(blank=True, choices=[('wickets', 'Wickets'), ('runs', 'runs')], max_length=10, null=True)),
                ('win_margin', models.PositiveIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main.match')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_teams', to='main.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='main.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='main.team'),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amt', models.PositiveSmallIntegerField(default=0)),
                ('win_lose_amt', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('default', 'Default'), ('won', 'Won'), ('lost', 'Lost'), ('noresult', 'No Result')], db_index=True, default='placed', max_length=10)),
                ('create_upd_time', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated', models.BooleanField(db_index=True, default=False)),
                ('bet_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_bets', to='main.team')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_bets', to='main.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
