# Generated by Django 3.2.8 on 2021-10-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_match_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('num',), 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='match',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
