# Generated by Django 3.2.8 on 2021-10-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211019_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchresult',
            options={'ordering': ('match__num',)},
        ),
    ]
