# Generated by Django 3.2.8 on 2021-10-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_bet_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='create_upd_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
