# Generated by Django 3.2.8 on 2021-10-20 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_alter_bet_create_upd_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ('create_upd_time',)},
        ),
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('match', 'user')},
        ),
    ]
