# Generated by Django 3.2.8 on 2021-10-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211021_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main.match', unique=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_standings', to='main.team', unique=True),
        ),
    ]
