# Generated by Django 3.2.8 on 2021-10-21 17:19

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211021_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='against_overs',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='against_runs',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='for_overs',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='for_runs',
        ),
        migrations.AddField(
            model_name='standing',
            name='against_rr',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[main.validators.score_validator]),
        ),
        migrations.AddField(
            model_name='standing',
            name='for_rr',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[main.validators.score_validator]),
        ),
    ]
