# Generated by Django 3.2.8 on 2021-10-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211022_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ('match', 'create_upd_time')},
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
